# Generated by Django 5.2 on 2025-04-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20),
        ),
    ]
